POST http://localhost:5050/app/register
Content-Type: application/json

{
    "userName": "John",
    "email": "john@gmail.com",
    "password":"John@123",
    "mobile": "8248869815"
}

# POST http://localhost:5050/app/login
# Content-Type: application/json

# {
#     "email": "john@gmail.com",
#     "password":"John@123"
# }

# GET http://localhost:5050/app/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkpvaG4iLCJpYXQiOjE2MzM4MTkwMDksImV4cCI6MTYzMzgxOTAyOX0.O9Hr6ZOWbIGjsyTDd__MERULKTKCbyEHUnfjss2vRnI

# POST http://localhost:5050/app/refresh-token
# Content-Type: application/json

# {
# "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkpvaG4iLCJpYXQiOjE2MzM4MTkwMDksImV4cCI6MTYzMzk5MTgwOX0.elexNGSXuKM8V8KpT3JntUeMamP2otxm3qcSe8PB4qQ"
# }


